### ISSUE TITLE
UWS Error

### ISSUE THREAD

**Issue by 34r7h** [coast-team/netflux#170]
warning " > netflux@4.3.1" has incorrect peer dependency "uws@10.148.1".

**Comment by 34r7h** [comment]
After installing uWebSockets.js and then changing the node_modules folder name to uws, the following error occurs.
`The new Group state is  0
/home/34r7h/xymnet/node_modules/netflux/dist/netflux.node.es5.cjs.js:1
TypeError: env.WebSocket is not a constructor
    at Signaling.connect (/home/34r7h/xymnet/node_modules/netflux/dist/netflux.node.es5.cjs.js:8197:23)
    at WebChannel.startJoin (/home/34r7h/xymnet/node_modules/netflux/dist/netflux.node.es5.cjs.js:10104:24)
    at WebChannel.join (/home/34r7h/xymnet/node_modules/netflux/dist/netflux.node.es5.cjs.js:9869:18)
    at WebGroup.join (/home/34r7h/xymnet/node_modules/netflux/dist/netflux.node.es5.cjs.js:10318:23)
    at Object.<anonymous> (/home/34r7h/xymnet/index.js:45:4)
    at Generator.next (<anonymous>)`
